"""Future Kroll desktop integration — interface only (PRD)."""

from __future__ import annotations

from typing import Any, Protocol


class IKrollAdapter(Protocol):
    """Adapter for automating the real Kroll by Telus Health desktop application."""

    def connect(self) -> bool: ...

    def open_patient(self, patient_id: str) -> None: ...

    def create_patient(self) -> None: ...

    def update_patient(self, data: dict[str, Any]) -> None: ...

    def save_patient(self) -> None: ...

    def search_patient(self, criteria: dict[str, str]) -> list[dict[str, str]]: ...

    def add_allergy(self, allergy: dict[str, str]) -> None: ...

    def add_condition(self, condition: dict[str, str]) -> None: ...

    def set_field_value(self, object_name: str, value: str) -> None: ...

    def get_field_value(self, object_name: str) -> str: ...
